baseurl: https://www.philosophicalhacker.com/
disablePathToLower: true
languageCode: en-us
title: Philosophical Hacker
theme: casper
DisqusShortname: philosophicalhacker
params:
    cover: images/cropped-thinker.jpg
    description: Thoughts on programming and startups from a wannabe philosophy professor turned wannabe tech entrepreneur
    twitterName: philosohacker
    facebookName: philosophicalhacker
    linkedinName: k-matthew-dupree-44672178
    googleAnalyticsUserID: UA-63544399-1
menu:
    main:
    - name: Home
      weight: -4
      identifier: blog
      url: /
    - name: Talks
      weight: -3
      identifier: talks
      url: /talk
    - name: Github
      weight: -2
      url: https://github.com/kmdupr33
    - name: Notes
      weight: -1
      identifer: notes
      url: /note
