baseurl: http://kmdupr33.github.io/
disablePathToLower: true
languageCode: en-us
title: Philosophical Hacker
theme: casper
params:
    cover: images/the-thinker.jpg
    description: Articles on android and go development
    twitterName: philosohacker
    facebookName: philosophicalhacker
    linkedinName: k-matthew-dupree-44672178
    googleAnalyticsUserID: UA-63544399-1
...
