baseurl: https://www.philosophicalhacker.com/
disablePathToLower: true
languageCode: en-us
title: Philosophical Hacker
theme: casper
DisqusShortname: philosophicalhacker
pygmentsCodefences: true
params:
    cover: images/black.jpg
    description: Thoughts on programming and startups from Matt Dupree, a wannabe philosophy professor turned wannabe tech entrepreneur living in Orlando
    twitterName: philosohacker
    facebookName: philosophicalhacker
    linkedinName: k-matthew-dupree-44672178
    googleAnalyticsUserID: UA-63544399-1
menu:
    main:
    - name: Home
      weight: -5
      identifier: blog
      url: /
    - name: RxJava O'Reilly Book
      weight: -4
      url: https://www.oreilly.com/programming/free/rxjava-for-android-app-development.csp?intcmp=il-prog-free-product-na_new_site_rxjava_for_android_app_development
    - name: Talks
      weight: -3
      identifier: talks
      url: /talk
    - name: Github
      weight: -2
      url: https://github.com/kmdupr33
    - name: Notes
      weight: -1
      identifer: notes
      url: /note
