baseurl: https://philosophicalhacker.com/
disablePathToLower: true
languageCode: en-us
title: Philosophical Hacker
theme: casper
DisqusShortname: philosophicalhacker
params:
    cover: images/cropped-thinker.jpg
    description: Articles on android development
    twitterName: philosohacker
    facebookName: philosophicalhacker
    linkedinName: k-matthew-dupree-44672178
    googleAnalyticsUserID: UA-63544399-1
menu:
    main:
    - name: "Home"
      weight: -120
      identifier: "blog"
      url: "/"
